# Generated by Django 3.2.7 on 2021-12-18 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('codigo', models.CharField(max_length=70, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('costo_unitario', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('utilidad', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('precioventa', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('descuento', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('importeiva', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('fechaultima', models.DateField(blank=True, null=True)),
                ('unidad', models.CharField(blank=True, max_length=50, null=True)),
                ('stock', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('stock_minimo', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('control_stock', models.BooleanField(blank=True, null=True)),
                ('stock_detallado', models.BooleanField(blank=True, null=True)),
                ('imagen', models.BinaryField(blank=True, null=True)),
            ],
        ),
    ]
