# Generated by Django 3.2.7 on 2021-12-18 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('idcategoria', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=70, null=True)),
                ('estado', models.IntegerField(blank=True, null=True)),
                ('trial879', models.CharField(blank=True, max_length=1, null=True)),
            ],
        ),
    ]
