# Generated by Django 3.2.7 on 2021-12-18 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_categorias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorias',
            name='trial879',
        ),
    ]
