# Generated by Django 3.2.7 on 2021-12-18 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_remove_categorias_trial879'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='idcategoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='general.categorias'),
            preserve_default=False,
        ),
    ]
