# Generated by Django 3.2.7 on 2021-12-18 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_productos_idcategoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='idcategoria',
        ),
    ]
